/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: fe8a089864392a293cd651eeb362988c)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/src/worker-entry");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
