/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 8020536dcc0c9c1c92ee88677541b085)
interface __BaseEnv_Env {
	EPISODES: R2Bucket;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/src/worker-entry");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
