/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 67b174befce10b0f58d984930c9e507a)
interface __BaseEnv_Env {
	EPISODES: R2Bucket;
	EPISODE_PROGRESS: D1Database;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/src/worker-entry");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
